### ISSUE TITLE
Face bug on tutorial code

### ISSUE THREAD

**Issue by JY132** [Optimization-AI/LibAUC#60]
Hi, Good day.

I was running the code from https://docs.libauc.org/examples/auroc.html

And I face this error when I try to load the data

for data, targets in trainloader:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\anaconda3\envs\dino\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Admin\anaconda3\envs\dino\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'ImageDataset' on <module '__main__' (built-in)>

I am using Jupyter Notebook to run the code with Python 3.10.14

**Comment by JY132** [comment]
Figured out how to debug it.

Just removing workers (num_workers argument) worked as a quick fix for me

**Comment by optmai** [comment]
Thanks!

**Comment by optmai** [comment]
Thanks!
